{"name":"Local: exception","url":"c:\\Projects\\ml-project\\src\\exception.py","tests":[{"id":1743918154270,"input":"","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"c:\\Projects\\ml-project\\src\\exception.py","group":"local","local":true}